title: Dublin Open Research Network
baseURL: https://dublinopenresearch.netlify.app/
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: DORN
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  ananke_socials:
    - name: twitter
      url: https://twitter.com/dublinopensci
    - name: mail
      url: mailto:dublinopenresearch@gmail.com
    - name: osf
      url: https://osf.io/x5ck6/
  author: ''
  background_color_class: bg-black
  description: Making Irish Research Open
  favicon: ''
  recent_posts_number: 3
  site_logo: 'Transparent Logo-02.png'
  text_color: ''
